- name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM and Build
        run: |
          npm install
          npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x ".git/*" ".github/*" "tests/*" "phpunit.xml" "README.md"
        # The key here is: DO NOT exclude 'vendor' or 'public/build'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip
